name: Run Python Script Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full repository is checked out for pushing changes

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Adjust the Python version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 pyyaml

      - name: Run Python Script
        run: python app.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Daily update: $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Push Changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
